export enum ContainerId {
    CHAT_MAIN = 'via-connect',
    CHAT_MAIN_FORM = 'via-connect__form',
    CHAT_MAIN_FORM_HEADER_CLOSE = 'via-connect__close_svg',
    CHAT_MAIN_FORM_HEADER = 'via-connect__header-wrapper',
    CHAT_MAIN_FORM_SUBMIT = 'via-connect__submit-btn',
    CHAT_MAIN_FORM_LOADING = 'via-connect__form-body_loading',
    CHAT_MAIN_FORM_BODY = 'via-connect__form-body',
    CHAT_MAIN_FORM_AGREEMENT = 'via-connect__agreement',
    CHAT_MAIN_FORM_CUSTOMER_PHONE = 'via-connect__customer-phone',
    CHAT_MAIN_FORM_CUSTOMER_MESSAGE = 'via-connect__customer-message',
    CHAT_MAIN_FORM_SUCCESS = 'via-connect_success',
    CHAT_MAIN_FORM_SUCCESS_PHONE = 'via-connect__success_phone',
    CHAT_MAIN_FORM_SUCCESS_TITLE = 'via-connect__success_title',
    CHAT_MAIN_FORM_SUCCESS_MESSAGE = 'via-connect__success_message',
    CHAT_MAIN_BANNER = 'via-connect__banner',
    CHAT_MAIN_SPEECH = 'via-connect__initial-message',
    CHAT_BUTTON_MAIN = 'via-connect-btn-container',
    CHAT_BUTTON_MAIN_BODY = 'via-connect-btn',
    CHAT_BUTTON_MAIN_ICON_CONTAINER = 'via-connect-btn__icon_container',
    CHAT_BUTTON_MAIN_ICON = 'via-connect-btn__svg',
    CHAT_GREETING_MAIN = 'via-connect-greeting-container',
    CHAT_GREETING_IMAGE = 'via-connect__greeting-img',
    CHAT_GREETING_BODY = 'via-connect__greeting-body',
    CHAT_GREETING_CLOSE = 'via-connect__greeting-close',
    FORM_INPUT_PHONE = 'via-connect__input_phone',
}
